global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'springBootMetrike'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['application1:8080']
        labels:
          application: 'OIMS_VC'